[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# The redirect rule is important, without it Netlify returns 404 on page refresh.
